import { useState } from 'react';
import { Plus, X } from 'lucide-react';
import GoalCard from '@/components/money/GoalCard';
export default function SavingsSection({ goals, onCreate, onContribute, onDelete }) {
  const [mode,setMode]=useState(null),[amount,setAmount]=useState(''),[name,setName]=useState(''),[target,setTarget]=useState('');
  const close=()=>{setMode(null);setAmount('');setName('');setTarget('');};
  const submit=e=>{e.preventDefault();mode==='new'?onCreate({name,target_amount:Number(target),saved_amount:0}):onContribute(mode,Number(amount));close();};
  return <section id="goals" className="rounded-3xl border border-slate-200/70 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold">Saving goals</h2><p className="text-sm text-slate-500">Small steps toward something big</p></div><button onClick={()=>setMode('new')} className="flex items-center gap-1 rounded-xl bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700"><Plus size={16}/>New goal</button></div><div className="mt-5 flex gap-4 overflow-x-auto pb-1">{goals.length?goals.map(g=><GoalCard key={g.id} goal={g} onAdd={setMode} onDelete={onDelete}/>):<button onClick={()=>setMode('new')} className="min-h-48 w-full rounded-2xl border-2 border-dashed border-slate-200 text-sm text-slate-400 transition hover:border-indigo-300 hover:text-indigo-600">Create your first dream goal</button>}</div>
  {mode&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-sm rounded-3xl bg-white p-6"><div className="flex justify-between"><h3 className="text-lg font-bold">{mode==='new'?'Create a goal':`Save for ${mode.name}`}</h3><button type="button" onClick={close}><X size={19}/></button></div><div className="mt-5 space-y-3">{mode==='new'?<><input required value={name} onChange={e=>setName(e.target.value)} placeholder="What are you dreaming of?" className="w-full rounded-xl border bg-slate-50 p-3"/><input required min="1" type="number" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Target amount" className="w-full rounded-xl border bg-slate-50 p-3"/></>:<input required min="1" type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount to add" className="w-full rounded-xl border bg-slate-50 p-3"/>}<button className="w-full rounded-xl bg-indigo-600 py-3 font-semibold text-white">{mode==='new'?'Create goal':'Add to savings'}</button></div></form></div>}</section>;
}